### ISSUE TITLE
Equal Opportunity Diversity Project course to be completed

### ISSUE THREAD

**Issue by LGSanders65** [LGSanders65/Equal-Opportunity-Diversity#1]
## TODO
*Courses left to be completed for my Equal Opportunity Diversity Project*
* [x] Add README.md file
* [x] Add images/design for Website
* [x] Add LICENSE
* [x] Email Feedback link
